### ISSUE TITLE
checkpoint 1 is ready for review

### ISSUE THREAD

**Issue by subu250** [subu250/IndieCosmeticProducts#2]
@pawaitemadisoncollege. checkpoint 1 is complete. I did create a new repository but the concept is a little different than before where the products use natural ingredients.

**Comment by pawaitemadisoncollege** [comment]
@subu250 

- [x] The indie project requirements include a delete scenario. Can you add a meaningful user story that includes a delete?
- [x] Can you provide a bit about the user story related to buying a product? This can be a complex task with things such as payment processes. I wonder if this might be a better stretch goal than mvp? Based on the application flow, it appears "buy product" might actually represent "add product"? Meaning adding a new product to the list of products the application knows about? If so, perhaps this IS an MVP, but needs to be renamed.
- [x] I noticed you have Hibernate Search in your list of technologies, but there isn't an MVP user story that involves searching. 
- [x] Project plan only goes out through week 3. Please list out the tasks you need to complete and assign them to weeks. I realize there may be some movement of tasks across weeks, but the goal here is to demonstrate your understanding of all the work that needs to be completed. 
- [ ] tasks.md includes details about finding products, but there isn't an MVP user story or screen for this.
- [ ] tasks.md seems to be missing details for many mvp user stories. 
- [ ] tasks.d View Product seems to actually be a Search Product. I would considering viewing a product as displaying all information for a single product. Searching would allow the user to enter some criteria about the product they are looking for - such as the name, ingredients, category.
- [x]  Can you explain your proposed use of "JDBCRealm used for authentication". Project requirements are for AWS Cognito or a similar tech.
- [x] Remember the time log should include all work completed for this class, both on the indie project and the weekly work.

**Comment by subu250** [comment]
Thank you for the update @pawaitemadisoncollege As per the project requirements, my project use  AWS Cognito for authentication.
I have updated checkpoint 1 as per feedback.

**Comment by pawaitemadisoncollege** [comment]
Nice job with the updates. 

It looks like the project plan items are all checked off which would generally indicate they are complete. Might make the most sense to leave them unchecked and then check them only when complete:
- [ ] incomplete item example
- [x] complete item example

**Comment by subu250** [comment]
sure. Thank you!
